import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Footer from "./components/Footer";

import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';


import AuthProvider from './components/AuthProvider';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fishbrain Ted",
  description: "Generated by create next app",
};

// do not cache this layout
export const revalidate = 0;

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main>
          <AuthProvider accessToken={accessToken}>{children}</AuthProvider>  
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
